@startuml

skinparam componentStyle uml2

package "'MedicoVeterinario' Aggregate" <<Rectangle>> {
	class MedicoVeterinario <<(A,#fffab8) Aggregate Root>> {
		String nome
		MedicoVeterinarioId id
		CRM crm
	}
	class MedicoVeterinarioId <<(V,DarkSeaGreen) Value Object>> {
		int medicoVeterinarioId
	}
	class CRM <<(V,DarkSeaGreen) Value Object>> {
		String conselho
		String numero
		String uf
	}
}
MedicoVeterinario --> MedicoVeterinarioId : id
MedicoVeterinario --> CRM : crm


@enduml
