@startuml

skinparam componentStyle uml2

component [GestaoVeterinarios]
component [AgendamentoServicos]
component [GestaoLojas]
component [ECommerce]
component [GestaoEntregas]
component [GestaoAssinaturas]
component [GestaoPasseadores]
component [BanhoTosa]
component [CFMV]

interface "Fornecedor" as Fornecedor
[GestaoVeterinarios] --> Fornecedor
Fornecedor <.. [AgendamentoServicos] : consume



@enduml
