@startuml

skinparam componentStyle uml2

component [AgendamentoContext]
note right of [AgendamentoContext]
Fornece as funcionalidades de 
agendamento para todos os contextos 
da empresa. 
end note
component [ServicosContext]
note right of [ServicosContext]
Fornece as funcionalidades de 
Banho, Tosa e Passeio. 
end note
component [VeterinariosContext]
note right of [VeterinariosContext]
Fornece as funcionalidades consulta 
médica. 
end note
component [ConselhoFederalVeterinariaContext]
note right of [ConselhoFederalVeterinariaContext]
Fornece as funcionalidades de 
gerenciamento dos cadastros de 
médicos veterinários. 
end note

interface "RESTful HTTP" as ServicosContext_to_AgendamentoContext
[AgendamentoContext] --> ServicosContext_to_AgendamentoContext : OPEN_HOST_SERVICE
ServicosContext_to_AgendamentoContext <.. [ServicosContext] : consume

interface "RESTful HTTP" as VeterinariosContext_to_AgendamentoContext
[AgendamentoContext] --> VeterinariosContext_to_AgendamentoContext : OPEN_HOST_SERVICE
VeterinariosContext_to_AgendamentoContext <.. [VeterinariosContext] : consume

interface "RESTful HTTP" as VeterinariosContext_to_ConselhoFederalVeterinariaContext
[ConselhoFederalVeterinariaContext] --> VeterinariosContext_to_ConselhoFederalVeterinariaContext
VeterinariosContext_to_ConselhoFederalVeterinariaContext <.. [VeterinariosContext] : use via ANTICORRUPTION_LAYER



@enduml
